
name: how-to-quickcheck
version: 0.0.1.0
ghc-options: -Wall -Werror -Wno-unused-matches

dependencies: 
  - base

executables:
  how-to-quickcheck:
    source-dirs: src
    main: Main.hs 

tests:
  test:
    source-dirs: test
    main: Spec.hs
    ghc-options: -main-is Spec
    dependencies:
        - QuickCheck
        - tasty-quickcheck
        - tasty

  base64-test:
    source-dirs: test
    main: Base64Test.hs
    ghc-options: -main-is Base64Test
    dependencies:
      - QuickCheck
      - tasty-quickcheck
      - tasty
      - quickcheck-instances
      - bytestring
      - sandi
      - regex-posix
      - containers
